import jsPDF from 'jspdf';
import { formatNumber, formatUSD } from './calculator';
import type { CalculationBreakdown } from './types';

export function generatePdf(b: CalculationBreakdown): void {
	const doc = new jsPDF({ unit: 'mm', format: 'a4' });
	const pageW = doc.internal.pageSize.getWidth();
	const date = new Date().toLocaleDateString('ru-RU', {
		year: 'numeric',
		month: 'long',
		day: 'numeric'
	});

	// Watermark
	doc.setTextColor(220, 220, 220);
	doc.setFontSize(48);
	doc.setFont('helvetica', 'bold');
	doc.saveGraphicsState();
	const gs = new (doc as any).GState({ opacity: 0.15 });
	doc.setGState(gs);
	doc.text('PRELIMINARY', pageW / 2, 150, { align: 'center', angle: 35 });
	doc.text('CALCULATION', pageW / 2, 175, { align: 'center', angle: 35 });
	doc.restoreGraphicsState();

	// Header
	doc.setTextColor(20, 20, 20);
	doc.setFontSize(22);
	doc.setFont('helvetica', 'bold');
	doc.text('ECOTAX DECLARATION', 20, 25);

	doc.setFontSize(10);
	doc.setFont('helvetica', 'normal');
	doc.setTextColor(100, 100, 100);
	doc.text(`Preliminary calculation · ${date}`, 20, 33);
	doc.text(`Ref: ETX-${Date.now().toString().slice(-8)}`, 20, 39);

	// Line
	doc.setDrawColor(20, 20, 20);
	doc.setLineWidth(0.6);
	doc.line(20, 45, pageW - 20, 45);

	// Parties
	doc.setTextColor(20, 20, 20);
	doc.setFontSize(11);
	doc.setFont('helvetica', 'bold');
	doc.text('PARTIES', 20, 55);

	doc.setFont('helvetica', 'normal');
	doc.setFontSize(10);
	doc.text(`Direction: ${b.country.name}`, 20, 63);
	doc.text(`Region: ${b.country.region}`, 20, 69);
	doc.text(`Country code: ${b.country.code}`, 20, 75);

	// Product
	doc.setFont('helvetica', 'bold');
	doc.text('PRODUCT DETAILS', 20, 90);

	doc.setFont('helvetica', 'normal');
	doc.setFontSize(10);
	doc.text(`Category: ${b.category.name}`, 20, 98);
	doc.text(`CO2 emission: ${formatNumber(b.co2EmissionKg, 2)} kg`, 20, 104);
	doc.text(`Base factor: ${formatNumber(b.category.baseFactor, 2)}`, 20, 110);

	// Breakdown
	doc.setFont('helvetica', 'bold');
	doc.text('BREAKDOWN', 20, 125);

	const rows: [string, string][] = [
		['Product eco fee', formatUSD(b.productEcoFee)],
		...(b.cbamCarbonFee > 0
			? [['CBAM carbon fee', formatUSD(b.cbamCarbonFee)] as [string, string]]
			: []),
		['Packaging EPR fee', formatUSD(b.packagingRecyclingFee)],
		['Subtotal', formatUSD(b.subtotal)],
		[`VAT (${(b.vatRate * 100).toFixed(0)}%)`, formatUSD(b.vatAmount)]
	];

	let y = 133;
	doc.setFont('helvetica', 'normal');
	doc.setFontSize(10);
	rows.forEach(([label, val]) => {
		doc.text(label, 20, y);
		doc.text(val, pageW - 20, y, { align: 'right' });
		y += 6;
	});

	// Total
	y += 4;
	doc.setDrawColor(20, 20, 20);
	doc.line(20, y - 2, pageW - 20, y - 2);
	doc.setFont('helvetica', 'bold');
	doc.setFontSize(14);
	doc.text('TOTAL DUE', 20, y + 5);
	doc.text(formatUSD(b.total), pageW - 20, y + 5, { align: 'right' });

	// Footer
	doc.setFontSize(8);
	doc.setFont('helvetica', 'normal');
	doc.setTextColor(130, 130, 130);
	doc.text(
		'This document is a preliminary calculation and does not constitute a customs declaration.',
		20,
		280
	);
	doc.text('Generated by EcoTax Calculator · Tariffs valid for 2026', 20, 285);

	doc.save(`ecotax-${b.country.code}-${Date.now()}.pdf`);
}
